/* Article content, single source of truth.
   Consumed by index.html (desktop WordPad windows) and by the dedicated
   article pages somatic-rag.html and mcp-inspector.html. */
window.SITE_ARTICLES = {
  'somatic-rag': {
    win: 'somatic',
    title: "You Can't Retrieve What You Don't Know You're Missing",
    description: "Agentic RAG, meet your other half. Somatic RAG: push the context the agent doesn't know it's missing, via harness hooks.",
    html: `
<h1>You Can't Retrieve What You Don't Know You're Missing</h1>
<p style="color:#555;margin-bottom:2px">May 2026</p>
<p><span class="tag">Agents</span><span class="tag">Memory</span><span class="tag">MCP</span><span class="tag">Hooks</span></p>
<p>There is a field in one of the systems I work on that has been deprecated for years and comes back empty every single time you read it. But it is named in such a way that every agent thinks that is the one field that they should really really focus on. And it's always empty! Thus, the agent declares it's the wrong environment and starts searching for the correct one among the local containers, tries to see if it assumed the wrong launch config, and basically goes tokenmaxxing on a wild goose chase.</p>
<p>The agent did nothing dumb, but still failed. The field had a name that sounded like it mattered, so it used it. "But is this secretly deprecated tho?" was missing from the agent's idea of what questions were worth asking. This would get a human maybe once or twice tops. But it will get the poor agent every time I don't end the prompt with "...and watch for that field. It's deprecated but not marked as such". This is basically how you get the next HAL, the next Skynet, the next Butlerian Jihad...</p>
<p>This is a long standing problem, because it is the one that no amount of better retrieval fixes, and almost everyone building agent memory right now is building better retrieval. We the agentic AI gourmands, have a tendency towards bit of a herd mentality. The sheer volume of buzz surrounding LLMs often turns a reasonable sounding hypothesis into an assumed fact, cascading into widespread architectural fallacies.</p>
<p>We have seen this happen with RAG, people assumed if there is enough cosine similarity (or HNSW with closest neighbors etc.) the relevant parts of context would elegantly surface. When this did not happen, it was "RAG is dead" or "Graph RAG is everything". In the process, RAG has changed meanings from simply augmenting the generation via retrieval, to using graph or vector searches with each prompt.</p>
<p>Ultimately the puzzle of retrieving the context that the agent doesn't know that it doesn't know, has not been solved as of yet. I didn't solve it either. But I will propose a design pattern, that I believe to be quietly and spontaneously climbing its way towards becoming the de facto standard. I will lay it out along with a lightweight library, that will enable you to personally observe why this pattern is empirically sound.</p>
<h2>Unknown unknowns</h2>
<p>I'm but a humble dev, and far be it from me to criticize Karpathy the magnifique. But he can at times be a great trigger of the herd mentality. He has recently come up with a lovely knowledge management paradigm called "LLM Wiki", a fairly decent pattern that hinges on 3 feet. Ingestion, querying and gardening. This 3 prong scheme has a glaring weakness that I'd like to criticize. This requires the agent to initiate the querying. The agent realizes it is unsure about something, forms a query, calls a tool, gets context back, carries on. Vector store, knowledge graph, grep over a notes folder, a Jira MCP, it does not matter. The pattern is the same. The agent decides it has a gap, then goes and fills it.</p>
<p>There is a precondition buried in that loop: the agent has to know the gap is there to <strong>pull</strong>. While recent models have shown improvement in this regard, you just can't rely on them as of now. LLMs are still notorious for just making up the gap. If a model sees "topic" and "publish" in your docs without explicitly naming the technology, it assumes Kafka and is like, "GCP who?". If it is supposed to pull a DLQ entry, it will waste a quarter of its context window trying to figure out the Kafka setup. Possibly even conclude the implementation is missing and start to implement one.</p>
<p>The half that is missing then, is <strong>push</strong>: something that finds the fact the agent lacks and injects it in the background. Something that will ask "Oh are we doing CQRS? Alright let me go find out about the messaging architecture".</p>
<h2>Somatic memory with hooks</h2>
<p>Firstly, we need to briefly explore what hooks are. Hooks are runtime events that the harness exposes. These are usually things like "Stop" where the LLM finishes responding or "UserSubmitPrompt" which fires when the user sends the prompt, but before it reaches the model. The user can attach executables to these events. These executables "automatically" run without intentional invocation by the agent. For instance, every time my model makes a tool call, a programlet can check if it contains banned commands. Or on SessionEnd, I can upload the conversation to somewhere.</p>
<p>Just as MCP protocol has become the standard for <strong>pull</strong> oriented tools, an emerging surface for <strong>push</strong> tooling is the hooks that are exposed by most harnesses. We will be utilizing both. Anthropic first published the MCP standard, now it looks like their hooks are becoming the standard. Below is a table for foremost legacy harnesses and a few recent up and coming ones, that adopt hooks with some divergence in their standards:</p>
<table>
<thead><tr><th>Harness</th><th>Cohort</th><th>User Submit hook equivalent</th><th>Wire contract vs Claude Code</th></tr></thead>
<tbody>
<tr><td>Claude Code (Anthropic)</td><td>established</td><td><code>UserPromptSubmit</code></td><td>original gangster</td></tr>
<tr><td>Codex CLI (OpenAI) / Qwen Code (Alibaba)</td><td>established / 2026</td><td><code>UserPromptSubmit</code></td><td>adopt it wholesale</td></tr>
<tr><td>Gemini CLI (Google)</td><td>established</td><td><code>BeforeAgent</code></td><td>adopts it, renames the events</td></tr>
<tr><td>Cursor (Anysphere)</td><td>established</td><td><code>beforeSubmitPrompt</code></td><td>its own vocabulary but maps to it</td></tr>
<tr><td>pi (Mario Zechner)</td><td>2026 newcomer</td><td><code>input</code></td><td>its own JS extension API, not stdin but adaptable</td></tr>
<tr><td>CodeWhale (formerly deepseek-tui)</td><td>2026 newcomer</td><td><code>message_submit</code></td><td>adopting it now (issue #1364)</td></tr>
</tbody>
</table>
<p>Look down that last column. An increasing percentage of harnesses either takes Claude Code's wire format wholesale or with a new vocabulary onto it, the most divergent example being pi. When I looked at the 7 of the high popularity harnesses that came out in 2026, I found 5 of them have hooks comparable to Anthropic's. The rate drops the earlier you go. So this is something of an "underground" movement among the cooler people for now.</p>
<p>What makes it worth pointing at is how little noise it made on the way in. MCP arrived with a campaign behind it. "USB-C for LLMs" was the line, it was a good line, and within a season not adopting MCP had started to look like a decision you would be asked to defend. Hooks got none of that, no "this is now the standard", and the harnesses settled on Claude Code's contract regardless, one after another, each of them arriving at the same need on its own. An "emergent" standard, where human was very much in the loop.</p>
<p>That retrieval step is a free variable. It can be grep over a folder of markdown, a vector store, a knowledge graph, or a NotebookLM instance that is filled with the past chats. Swap one for another and nothing above it has to move. You have your body of knowledge and a sense of what the unknown unknowns can be. The design pattern around it can be relatively stable. In fact, let us do a minimal hands on experiment with it.</p>
<h2>A small library you can run</h2>
<p>Back near the top I promised a small library you could run yourself to watch the pattern in operation. It is at: <a href="https://github.com/esinecan/somatic-memory">github.com/esinecan/somatic-memory</a></p>
<p>It is called somatic-memory for now. Not the best name since the MCP half of it is opposite of somatic. Somatic systems of the body work without our conscious input. The speed of your pulse increases as your muscle output does. It doesn't require you to think "Let me send more blood to my calves". Your iris reacts to light.</p>
<p>Which is why only one of the two components fits the name. The hook is truly "somatic". It fires on your prompt and pushes context in before the model reads a word, no action from the model needed. Like the iris reacting to light. But we do also squint when it's too bright right? The other component is a plain MCP tool called recall, and the agent reaches for it the moment it knows it has a gap. That one is a deliberate, conscious query, the exact opposite of somatic (agentic?), and corresponds to the squint.</p>
<p>In the end, all this engine does one small thing: given the conversation, hand back what is relevant. Because it only reads and never writes, the thing it reads from is entirely up to you: a folder, a vault, a database, a live search. The library calls each one an oracle. Treat them as scaffolding for your customizations. Although the ones besides Web oracle are legitimately usable as is.</p>
<table>
<thead><tr><th>Oracle</th><th>What it reads</th></tr></thead>
<tbody>
<tr><td>filesystem</td><td>a folder of text files, the zero-config default</td></tr>
<tr><td>obsidian</td><td>the same, plus it follows wikilinks one hop into linked notes you never searched for</td></tr>
<tr><td>sqlite</td><td>full-text search over a database something else filled</td></tr>
<tr><td>web</td><td>a live search fetch, for a source you neither own nor wrote</td></tr>
</tbody>
</table>
<p>Swap one row for another and nothing above it has to change. That is the free variable from earlier. I point my own setup at a cloud notebook I already keep, NotebookLM as it happens, but the filesystem oracle needs no cloud and no account at all. The plainest version is grep over a folder of notes, and that already does most of the work. A surprisingly effective way that I will always stand by.</p>
<h2>The design space</h2>
<p>The library above is aimed being the simplest representation of a design pattern. To me, contextsmithing via harness hooks (setting aside "which hook" question) have 4 basic axes. These are immediate angles to fork and tailor the project above for yourself:</p>
<p>1. <strong>Personal against institutional:</strong> A continuity setup remembers one person across their own sessions and harnesses, the daemon that has been reading over your shoulder for months. An institutional one holds what a team or an org knows, the shared store every member's agents read from. The engine is the same. What changes is whose memory it is and who it answers for.</p>
<p>2. <strong>Cloud against local:</strong> The oracle can be a hosted thing you query over the network, a cloud notebook or a managed database, or it can be a folder of files on your own disk that you search with grep. Nothing in the pattern prefers one. A simple folder somewhere in C:/, containing just a bunch of lowly, barely past stone age txt files, that get ripgrepped, synthesized and pushed to the main agent's context in a "somatic" manner, is genuinely surprisingly beneficial.</p>
<p>3. <strong>Read only against bidirectional:</strong> Everything so far only reads. A bidirectional version also writes, noticing when you correct the agent and keeping that lesson for next time. The write path is where the real difficulty lives, telling a genuine correction from a passing change of mind and keeping the store from rotting as it fills, which is why it is a later piece and not this one.</p>
<p>4. <strong>Sync against async:</strong> A sync hook blocks the prompt going to LLM until the context is assembled. An async one fires and lets the context arrive some time (depending on what you're having it do) later, while the agent is already working. A fully autonomous run, no human, can afford to block, and blocking means the agent does not start down a wrong path. But in interactive sessions a non-blocking somatic retrieval would be the smarter choice. The past context maybe arrives a little later in the background. I can afford that while I am actively monitoring.</p>
<p>A fair worry at this point is cost. A fresh retrieval pass on every prompt sounds like a lot. The push agent's brain is yours to size, though. At the cheap end it is regex and heuristic tomfoolery that never calls a model at all. At the other end it is the most capable, most "too dangerous to ship" frontier model you can find. Cost and speed move with that choice.</p>
<p>This is just one framing of the architecture, and probably not a complete one. None of the four axes has a default answer either. At work you might want the whole team sharing a cloud, knowledge-graph oracle that can also do backflips. For your very first home assistant, a filesystem ripgrep that returns thirty lines on either side of each hit could be plenty.</p>
<p>The middle ground keeps getting cheaper. Slotting in a small local model to run smarter searches used to be a luxury, but with capable local models everywhere now it often costs less than letting the main model go exploring on its own. Let's walk through a couple of concrete setups:</p>
<p>My home setup could be categorized as "personal, cloud, unidirectional, async" based on these axes. For home PCs of myself and my wife, I have notebooklm instances that are asked up to 3 questions by a Deepseek agent who interpreted the whole context. Once its questions are answered, same Deepseek agent synthesizes its tips and injects back into context between "&lt;subconscious&gt;" tags. It's a rather hefty one but it's great at creating the UX of one continuous identity. The agent only does read only stuff. Our chats are wholesale ingested into NotebookLM instances by a separate cron job.</p>
<p>When I was going to write this article, I scoured the land for similar architectures. It was a great sanity check to find Tomaz Bratanic's <a href="https://towardsdatascience.com/unified-agentic-memory-across-harnesses-using-hooks/">Neo4j based setup</a> that has a very similar design. I can sense the 4 axes in his thinking as well: "personal, local, bidirectional, and sync". It is personal in the same sense mine is, one developer's memory carried across Claude Code, Codex and Cursor. It is local, a Neo4j DB he runs himself instead of a hosted service. He has a "dream phase" implementation that corresponds to linting and ingestion phases of Papa Karpathy's "LLM Wiki" but similar to mine, it is decoupled from the hook + mcp remembering architecture, but because his hooks log every event into Neo4j, it is bidirectional.</p>
<p>I have also found some fellow travelers in CodeWhale. I liked it quite a lot as a community driven tool and wanted to try out, but its hooks could watch a user message go by without changing it, so the somatic injection I lean on elsewhere had no clean way in. So I filed an issue (<a href="https://github.com/Hmbown/CodeWhale/issues/1364">#1364</a>) asking for two things: a message_submit hook that can actually rewrite the text before it reaches the model, and a turn-end event for the fire-and-forget critique pass. What happened next was the encouraging part. The maintainer (<a href="https://github.com/Hmbown">Hmbown</a>) agreed it made sense, another contributor (<a href="https://github.com/LeXwDeX">LeXwDeX</a>) argued the hook layer should just mirror Claude Code's contract one to one, a third (<a href="https://github.com/AresNing">AresNing</a>) wrote the first implementation, and within weeks the maintainer put it together into a PR. I did not have to push any of it along. The thread filled up with people who already wanted the same thing, which is that quiet convergence from the table happening right in front of me, one human-in-the-loop decision at a time.</p>
<p>Pull already has a name, agentic RAG, and the MCP tool in here is exactly that, kept for every time the agent does know it has a gap. The push half never got one, neglected maybe in the backwash of semantic RAG disillusionment. I call it somatic RAG. Agentic RAG, meet your other half. My setup runs both against the same memory stores, and I do not read them as a trade-off.</p>
<p>So go back to that field from the start. The agent that burned a third of its window chasing the wrong environment was not stupid and was not short on retrieval. It failed because the one fact that would have saved it, that the field is dead and comes back empty, was never in its idea of what to ask. No bigger window and no better embedding reaches that, because the query never fires. The only thing that reaches it is something already watching the conversation, probing near that fact, ready to rush it back the moment it surfaces. You cannot retrieve what you do not know you are missing. Something else has to push it to you.</p>
<p>This skeleton will get converged on from a lot of directions, with write-back, team versions, gardeners and ontologies layered on top. The code is at the repo, the name is a placeholder, and there is nothing to install. Clone it, point it at a folder of your own notes, and wait for it to surprise you with some nuance you forgot you knew.</p>
<p style="margin-top:14px;border-top:1px solid #c0c0c0;padding-top:8px;color:#333">The code is at <a href="https://github.com/esinecan/somatic-memory">github.com/esinecan/somatic-memory</a>. The name is a placeholder, and there is nothing to install.</p>
`
  },
  'mcp-inspector': {
    win: 'mcpinsp',
    title: "An MCP tool to let AI debug any MCP server on the fly",
    description: "An MCP server that connects to other MCP servers, so the AI assistant can test and debug them from inside the same conversation.",
    html: `
<h1>An MCP tool to let AI debug any MCP server on the fly</h1>
<p style="color:#555;margin-bottom:2px">April 2026</p>
<p><span class="tag">MCP</span><span class="tag">TypeScript</span><span class="tag">Meta-Tooling</span><span class="tag">DevEx</span></p>
<p>Here is a non-exhaustive list of things that are now MCP tools in my daily workflow: NotebookLM notebooks. Google Sheets. A Playwright browser. Datadog dashboards. MongoDB queries. Jira and Confluence. kubectl. Who needs a babysitter, when I can connect my tamagotchi to an LLM over USB-C.</p>
<p>Every one of these integrations was built iteratively, tested live, and debugged from inside the same AI conversation that uses them. I liked the idea of exposing things as tools to AI the moment I heard it. Then you can abstract away a lot of the predictable and complex parts like injecting a cluster name into a kubectl command. But the problem is, it is pretty tricky to build that many tools each with their own individual needs.</p>
<p>That is why I have constructed a mcp server that can be used to connect to any mcp server. It was inspired by mcp-inspector initially, so I named it <a href="https://github.com/esinecan/mcp-inspector-as-mcp-server">mcp-inspector-as-mcp-server</a>. It's 400 lines of TypeScript and the MCP SDK is its only dependency. It is a simple tool but it really changed my mental model of tool building.</p>
<h2>"One tool to test them all"</h2>
<p>MCP is a good protocol with a terrible development experience.</p>
<p>Because MCP is a relatively new protocol with multiple transports, and JSON-RPC among them is a particularly problematic one to debug, it can be quite frustrating to develop an mcp server over the regular mcp-inspector through trial and error. In the age of AI, I want to be able to let my AI assistant loose on the broken draft, give it the response body I am going for, and have it iterate over the code until the nuts and bolts are set up correctly for it to run.</p>
<p>The idea is simple enough to fit in a sentence: make the MCP Inspector itself an MCP server, so your AI assistant can inspect and test other MCP servers from inside the conversation where it's going to use them.</p>
<p>This enables you to have the agent connect to a server, list and call the tools and observe the error messages within the context of a single chat.</p>
<pre><code>You:     "Connect to the new pricing MCP server and test the rate lookup tool"
Claude:  [calls insp_connect] -> session established
         [calls insp_tools_list] -> 14 tools found
         [calls insp_tools_call: get_rate] -> works, returns rate object
         [calls insp_tools_call: get_rate with bad input] -> 500, missing field validation
         "Rate lookup works but crashes on missing fields. Want me to fix the server?"</code></pre>
<p>That is essentially the entire development loop without a context switch.</p>
<h2>Sessions that survive</h2>
<p>Similar to ye olde HTTP calls, MCP tool calls themselves are stateless, but the server behind may or may not be. That's why the tool is designed with sessions so that servers where tool calls mutate the state can also be tested. <code>insp_connect</code> returns a <code>session_id</code> that subsequent calls reuse, with a 30-minute idle TTL and automatic garbage collection handling the lifecycle.</p>
<p>The same tools also work without a session ID for quick one-off inspections, so both stateful debugging and ephemeral checks go through the same interface.</p>
<h2>The event buffer</h2>
<p>Every session wraps its transport in a tracing layer that captures all traffic into a ring buffer of 1000 events. JSON-RPC messages in and out, notifications, errors, all in order.</p>
<pre><code>[calls insp_read_events with session_id, types: ["error"]]
-> 3 errors in last 5 minutes:
   1. "Invalid params: expected string for 'shipmentId', got number"
   2. "Timeout after 30s on get_shipment_360"
   3. "Connection reset during batch operation"</code></pre>
<p>This turns "it doesn't work" into a timeline of exactly what went wrong. The ring buffer keeps memory bounded even in long sessions since oldest events drop when it fills, so you lose ancient history but never run out of memory.</p>
<p>The implementation required solving a timing bug in the MCP SDK: the Protocol class sets handler callbacks after calling <code>transport.start()</code>, which means any wrappers you set in <code>start()</code> get overwritten. The fix was using JavaScript getters and setters to intercept handler assignment dynamically. The SDK sets the handler, our setter wraps it with tracing, and forwards the wrapped version. Clean, no SDK patches required.</p>
<h2>Steering from the outside</h2>
<p>This bit is low key pretty chill:</p>
<p>When an AI assistant is testing an MCP server, sometimes you want to nudge it without interrupting the conversation flow. Try the error path. Focus on that timeout. Skip auth, I'll fix it later.</p>
<p>The inspector has a steering mechanism. A simple FIFO queue per session. You inject a message, either through the <code>insp_inject_steering</code> tool or via a tiny HTTP API on port 9847. It gets delivered on the next tool response as a second content block.</p>
<pre><code># From your terminal, while the AI is working:
./mcp-steer "skip the auth tests, focus on rate compilation"</code></pre>
<p>The AI's next tool call comes back with two blocks: the actual result, and your steering message prefixed with a lightning bolt. If you remembered that "oh you need to call the rate update before you reprice the line items," you do not need to interrupt the agent and type this. You can simply inject the steering message.</p>
<p>Although my initial instinct was to overdesign with websockets and streaming, I ended up going simple when it comes to steering. Queue up, drain on next call. The simplicity is the point. Steering doesn't need to be real-time. It needs to be reliable and not add complexity to the MCP protocol itself.</p>
<h2>Why this matters beyond debugging</h2>
<p>Once you have a tool that can connect to any MCP server with full observability, iterative integration becomes possible almost for free.</p>
<p>You get the rough draft together, tell the AI "a success response should look like this," and let it loop. Test, find the bug, fix, restart, repeat.</p>
<p>And because the inspector handles all three MCP transports (stdio for local processes, SSE for remote servers, streamable HTTP), it actually covers majority of the possible use cases in its niche. Local dev server, remote environment behind an API, or if you're into suffering, even SSE.</p>
<p>This is what made the absurd integration list at the top of this article possible. Each of those was an afternoon of iterative development with the inspector keeping the feedback loop tight. The inspector removes the overhead that makes "just slap an MCP layer on it" feel daunting.</p>
<h2>The meta-tooling thesis</h2>
<p>As tool ecosystems grow you inevitably need tools about tools. MCP, though flawed, seems to have become the norm as it was intended to be from the beginning, and in the same way you need a debugger for your code and an inspector for your network requests, you need an inspector for your tool layer.</p>
<p>If you're building MCP servers, this is something I'd absolutely recommend. While far from being a silver bullet, it very reliably solves one specific and very common problem.</p>
<p>400 lines. One dependency. Give it a go. E-mail me if you like it. I will definitely get back 60% of the time.</p>
<p style="margin-top:14px;border-top:1px solid #c0c0c0;padding-top:8px;color:#333">The code is at <a href="https://github.com/esinecan/mcp-inspector-as-mcp-server">github.com/esinecan/mcp-inspector-as-mcp-server</a>. Single npm dependency. MIT licensed.</p>
`
  }
};
